on:
  workflow_dispatch:
  schedule:
    - cron: '45 19 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/or1cl2s-d3sa4m@cron
        with:
          token: ${{ secrets.token }}
